name: ReactWebsite CICD

on:
  push:
    branches: [ "main" ]

jobs:
  aws-configuration:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
        
  terraform-init:
    steps:
    - name: Terraform Version Check
      run: terraform --version
    - name: Terraform Init
