name: TerraformCICD

on:
  workflow_dispatch:
    inputs:
      ENVRIONMENT:
        type: choice
        description: 'EnvironmentName'
        required: true
        options: 
        - test
        - prod
        - dev
      STATEBUCKET:
        type: choice
        description: 'BucketName'
        required: true
        options: 
        - tf-state-bucket1
      STATEKEY:
        type: choice
        description: 'StateKey'
        required: true
        options: 
        - s3-bucket
        - s3-bucket2
        - s3-bucket3
      STATEREGION:
        description: 'Region of bucket'
        required: true
        default: 'ap-south-1'

jobs:
  terraform-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - uses: actions/checkout@v3
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: ls
      - name: Change Dir
        run: cd services/${{ github.event.inputs.STATEKEY }}/
      - run: pwd
      - run: cd ./services/s3-bucket/
      - run: pwd
      - name: Terraform Version Check
        run: terraform --version
      - name: Terraform Init
        run: terraform init -upgrade -backend-config="bucket=${{ github.event.inputs.STATEBUCKET }}" -backend-config="key=${{ github.event.inputs.ENVRIONMENT }}/${{ github.event.inputs.STATEKEY }}/terraform.tfstate" -backend-config="region=${{ github.event.inputs.STATEREGION }}"
        working-directory: ./services/${{ github.event.inputs.STATEKEY }}
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./services/${{ github.event.inputs.STATEKEY }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./services/${{ github.event.inputs.STATEKEY }}
